SET LINESIZE 2000;
--INSERT TOOLS CAT
INSERT INTO TOOLS_CATEGORY VALUES ('','COMMON TOOLS');
INSERT INTO TOOLS_CATEGORY VALUES ('','ENGINE SPECIAL TOOLS');
INSERT INTO TOOLS_CATEGORY VALUES ('','FRAME SPECIAL TOOLS');
INSERT INTO TOOLS_CATEGORY VALUES ('','ELECTIC SPECIAL TOOLS');
INSERT INTO TOOLS_CATEGORY VALUES ('','MEASUREMENT TOOLS');
INSERT INTO TOOLS_CATEGORY VALUES ('','STRATEGIC TOOLS');

--INSERT TOOLS
INSERT INTO TOOLS VALUES ('','KUNCI SOK / SOCKET SET', 'CAT001',1);
INSERT INTO TOOLS VALUES ('','KUNCI "L" HEXAGONAL', 'CAT001',1);
INSERT INTO TOOLS VALUES ('','KUNCI "L" TORX', 'CAT001',1);
INSERT INTO TOOLS VALUES ('','IMPACT SCREWDRIVER', 'CAT001',1);
INSERT INTO TOOLS VALUES ('','PNEUMATIC IMPACT WRENCH', 'CAT001',1);

INSERT INTO TOOLS VALUES ('','Flywheel Puller', 'CAT002',1);
INSERT INTO TOOLS VALUES ('','Flywheel Holder', 'CAT002',1);
INSERT INTO TOOLS VALUES ('','Gear Holder', 'CAT002',1);
INSERT INTO TOOLS VALUES ('','Valve Spring Compressor', 'CAT002',1);
INSERT INTO TOOLS VALUES ('','Lock Nut Wrench', 'CAT002',1);

INSERT INTO TOOLS VALUES ('','Spoke Wrench', 'CAT003',1);
INSERT INTO TOOLS VALUES ('','Wheel Truing', 'CAT003',1);

INSERT INTO TOOLS VALUES ('','DLC Short Connector', 'CAT004',1);
INSERT INTO TOOLS VALUES ('','PIN Probe Male', 'CAT004',1);
INSERT INTO TOOLS VALUES ('','HDS(Honda Diagnosa System)', 'CAT004',1);
INSERT INTO TOOLS VALUES ('','Jumpel Line', 'CAT004',1);

INSERT INTO TOOLS VALUES ('','Feeler Gauge / Thickness Gauge', 'CAT005',1);
INSERT INTO TOOLS VALUES ('','Mistar Baja', 'CAT005',1);
INSERT INTO TOOLS VALUES ('','Jangka Sorong / Caliper', 'CAT005',1);
INSERT INTO TOOLS VALUES ('','Outside Micrometer', 'CAT005',1);
INSERT INTO TOOLS VALUES ('','Inside Micrometer', 'CAT005',1);

INSERT INTO TOOLS VALUES ('','Obeng (+)', 'CAT006',1);
INSERT INTO TOOLS VALUES ('','Obeng (-)', 'CAT006',1);
INSERT INTO TOOLS VALUES ('','Obeng Stubby', 'CAT006',1);
INSERT INTO TOOLS VALUES ('','Obeng Electic (+)', 'CAT006',1);
INSERT INTO TOOLS VALUES ('','Obeng Electic (-)', 'CAT006',1);

--INSERT SPAREPART_CATEGORY
INSERT INTO SPAREPART_CATEGORY VALUES ('', 'BEARING');
INSERT INTO SPAREPART_CATEGORY VALUES ('', 'BOLT');
INSERT INTO SPAREPART_CATEGORY VALUES ('', 'LAINNYA');

--INSERT SPAREPART
INSERT INTO SPAREPART VALUES ('', 'BEARING Ball 6203', 'SC001', 0, 'Bearing Ball 6203');
INSERT INTO SPAREPART VALUES ('', 'BEARING Ball 6303', 'SC001', 0, 'Bearing Ball 6303');
INSERT INTO SPAREPART VALUES ('', 'BEARING Ball Radial 6301U L', 'SC001', 0, 'Bearing Ball Radial 6301U L');
INSERT INTO SPAREPART VALUES ('', 'BEARING Radial 6301', 'SC001', 0, 'Bearing Radial 6301');
INSERT INTO SPAREPART VALUES ('', 'BEARING Radial N/COM', 'SC001', 0, 'Bearing Radial N/COM');

INSERT INTO SPAREPART VALUES ('', 'BOLT Socket 8x32', 'SC002', 0, 'BOLT Socket 8x32');
INSERT INTO SPAREPART VALUES ('', 'BOLT Socket 8x32', 'SC002', 0, 'BOLT Socket 8x32');
INSERT INTO SPAREPART VALUES ('', 'BOLT Socket 8x32', 'SC002', 0, 'BOLT Socket 8x32');

--INSERT HTRANS
INSERT INTO HTRANS VALUES ('', TO_DATE('19/12/2022', 'DD/MM/YYYY'), 'Fernando', 'Jl. Ngagel Jaya Tengah No. 71', '1234567890123456', '219116828', 'N 1234 RR', 'Honda Vario', 100000, 1);

--INSERT DTRANS


commit;