CREATE TABLE TOOLS_CATEGORY(
	ID_KATEGORI VARCHAR2(9) PRIMARY KEY,
	-- CAT/001
	NAMA VARCHAR2(20) NOT NULL
);

CREATE TABLE TOOLS(
	ID_TOOLS VARCHAR2(9) PRIMARY KEY,
	-- AHASS/001
	NAMA VARCHAR2(20) NOT NULL,
	ID_KATEGORI VARCHAR2(9),
	STATUS NUMBER(1) NOT NULL,
	-- 0 = not available, 1 = available
	FOREIGN KEY (ID_KATEGORI) REFERENCES TOOLS_CATEGORY(ID_KATEGORI) 
);

CREATE TABLE CABANG(
	ID_CABANG VARCHAR2(9) PRIMARY KEY,
	DAERAH VARCHAR2(20) NOT NULL,
	KOTA VARCHAR2(20) NOT NULL,
	ALAMAT VARCHAR2(20) NOT NULL
);

CREATE TABLE SPAREPART_CATEGORY(
	ID_CATEGORY VARCHAR2(9) PRIMARY KEY,
	CATEGORY_NAME VARCHAR2(20) NOT NULL
);

CREATE TABLE SPAREPART(
	ID_SPARE VARCHAR2(9) PRIMARY KEY,
	NAME VARCHAR2(20) NOT NULL,
	ID_CATEGORY VARCHAR2(20) NOT NULL,
	FOREIGN KEY (ID_CATEGORY) REFERENCES SPAREPART_CATEGORY(ID_CATEGORY)
);

CREATE TABLE STOK_SPAREPART(
	ID VARCHAR2(3) PRIMARY KEY,
	ID_SPARE VARCHAR2(9) NOT NULL,
	ID_CABANG VARCHAR2(9) NOT NULL,
	FOREIGN KEY (ID_SPARE) REFERENCES SPAREPART(ID_SPARE),
	FOREIGN KEY (ID_CABANG) REFERENCES CABANG(ID_CABANG)
);