DROP TABLE TOOLS PURGE;
DROP TABLE STOK_SPAREPART PURGE;
DROP TABLE SPAREPART;
DROP TABLE TOOLS_CATEGORY PURGE;
DROP TABLE CABANG PURGE;
DROP TABLE SPAREPART_CATEGORY PURGE;

CREATE TABLE TOOLS_CATEGORY(
	ID_KATEGORI VARCHAR2(9) PRIMARY KEY,
	-- CAT/001
	NAMA VARCHAR2(20) NOT NULL
);

CREATE TABLE TOOLS(
	ID_TOOLS VARCHAR2(9) PRIMARY KEY,
	-- AHASS/001
	NAMA VARCHAR2(20) NOT NULL,
	ID_KATEGORI VARCHAR2(9),
	STATUS NUMBER(1) NOT NULL,
	-- 0 = not available, 1 = available
	FOREIGN KEY (ID_KATEGORI) REFERENCES TOOLS_CATEGORY(ID_KATEGORI) 
);

CREATE TABLE CABANG(
	ID_CABANG VARCHAR2(9) PRIMARY KEY,
	DAERAH VARCHAR2(20) NOT NULL,
	KOTA VARCHAR2(20) NOT NULL,
	ALAMAT VARCHAR2(20) NOT NULL
);

CREATE TABLE SPAREPART_CATEGORY(
	ID_CATEGORY VARCHAR2(9) PRIMARY KEY,
	CATEGORY_NAME VARCHAR2(20) NOT NULL
);

CREATE TABLE SPAREPART(
	ID_SPARE VARCHAR2(9) PRIMARY KEY,
	NAME VARCHAR2(20) NOT NULL,
	ID_CATEGORY VARCHAR2(20) NOT NULL,
	DESCRIPTION VARCHAR2(50) NOT NULL,
	FOREIGN KEY (ID_CATEGORY) REFERENCES SPAREPART_CATEGORY(ID_CATEGORY)
);
-- data sparepart semua cabang
CREATE TABLE STOK_SPAREPART(
	ID VARCHAR2(3) PRIMARY KEY,
	ID_SPARE VARCHAR2(9) NOT NULL,
	ID_CABANG VARCHAR2(9) NOT NULL,
	FOREIGN KEY (ID_SPARE) REFERENCES SPAREPART(ID_SPARE),
	FOREIGN KEY (ID_CABANG) REFERENCES CABANG(ID_CABANG)
);

CREATE TABLE DATA_KENDARAAN(
	ID_KENDARAAN VARCHAR2(14) PRIMARY KEY,
	-- /<index>(3 digit)/tgl(dd-mm-yy)/kodecabang
	NAMA_PEMILIK VARCHAR2(50) NOT NULL,
	ALAMAT_PEMILIK VARCHAR2(50) NOT NULL,
	NO_KTP VARCHAR2(18) NOT NULL,
	NPWP VARCHAR2(20),
	NO_POLISI VARCHAR2(20) NOT NULL,
	DESKRIPSI_KENDARAAN VARCHAR2(50),
	NO_INVOICE VARCHAR2(30) NOT NULL
);

-- comment yang punya sendiri
-- field 1 = username
-- field 2 = password 
-- field 3 = tns listener name
-- CREATE PUBLIC DATABASE LINK cabdave CONNECT TO admin IDENTIFIED BY admin USING 'cabdave';